sudo: required

language: go

services:
  - docker

before_install:
  - wget https://releases.hashicorp.com/terraform/0.11.7/terraform_0.11.7_linux_amd64.zip
  - unzip terraform_0.11.7_linux_amd64.zip

branches:
  only:
    - master
    
script:
  - ./terraform init ./emr
