version: 2
jobs:
  test-code:
    docker:
      - image: hashicorp/packer
    steps:
      - checkout
      - run:
          name: Download terraform
          command: wget https://releases.hashicorp.com/terraform/0.11.7/terraform_0.11.7_linux_amd64.zip
      - run:
          name: Unzip terraform binary
          command: unzip terraform_0.11.7_linux_amd64.zip
      - run:
          name: Terraform init
          command: ./terraform init ./emr
      - run:
          name: Terraform apply
          command: ./terraform apply --auto-approve ./emr
      - run:
          name:  Terraform destroy
          command: ./terraform destroy --auto-approve ./emr
          when: on_fail
  destroy-test-code:
    docker:
      - image: hashicorp/packer
    steps:
      - checkout
      - run:
          name: Download terraform
          command: wget https://releases.hashicorp.com/terraform/0.11.7/terraform_0.11.7_linux_amd64.zip
      - run:
          name: Unzip terraform binary
          command: unzip terraform_0.11.7_linux_amd64.zip
      - run:
          name: init to clear test code
          command: ./terraform init ./emr
      - run:
          name: destroy test code
          command: ./terraform destroy --auto-approve ./emr

workflows:
  version: 2
  agendaedu-test-by-commits:
    jobs:
      - test-code:
          filters:
            branches:
              only:
                - master
            tags:
              ignore: /.*/
      - destroy-test-code:
          requires:
            - test-code
          filters:
            branches:
              only:
                - master
            tags:
              ignore: /.*/
